services:
  - type: web
    name: sms-spam-node-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: sms-spam-python-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT spam_api:app
    healthCheckPath: /
    envVars:
      - key: CORS_ORIGIN
        sync: false
